### ISSUE TITLE
Category Request

### ISSUE THREAD

**Issue by Officialethnerd** [Zimtente/ens-collections#1]
Name: “emoji hex 1 digit club”
Slug: “emojihex-1digitclub”
Description: “names with all emojis using hex plus one digit”
Twitter: N/A
website: N/A
Chat: N/A
Logo: N/A
Csv: see attached picture 
![69A75F08-C6CD-4F28-B6D1-71041F99D8AA](https://user-images.githubusercontent.com/106839511/171937931-d354ff72-7ac5-47a3-b41c-5dfe266628a1.jpeg)

**Comment by tunnckoCore** [comment]
meh :D

**Comment by Officialethnerd** [comment]
Is that a yes or no? That doesn’t help me determine my next steps. Please advise.

**Comment by tunnckoCore** [comment]
Don't worry, it's okay, I'm not part of the core team.

You can check some of the pull requests, i gave some help there.

**Comment by Officialethnerd** [comment]
Just saying there are possibly more people than me who have never used github. The coding may look foreign. I am sure you get what I am trying to submit.

**Comment by tunnckoCore** [comment]
@Officialethnerd 

Sure, don't worry.

We will have automated and easier request submission, and probably a voting on those requests somewhere like ens.vision.

**Comment by Officialethnerd** [comment]
Thank you

**Comment by Officialethnerd** [comment]
README.md

**Comment by shukaeth** [comment]
Categories on en.vision are on hold right now, as we will release a new solution soon.
We reserve the right to publish categories that we consider important in the meantime.
A new system be available soon, so that there will be an option for everyone to proper categorize their address. 

Thank you for your kindness and your patience in the meantime!
