### ISSUE TITLE
Hey! Lastname, spoke on discord

### ISSUE THREAD

**Issue by themichaelk** [Zimtente/ens-collections#101]
Hey, my name is errol. I have bought the last name stackpool from premium, and noticed it's not listed as a lastname, so here you go some proof :)
<img width="944" alt="Screen Shot 2022-07-04 at 11 24 00" src="https://user-images.githubusercontent.com/108685760/177191950-090bf2c9-f908-4a6c-b379-227b8246bb50.png">

Thank you!

**Comment by tunnckoCore** [comment]
Thanks for the "proof" but..

There are millions and billions of names, surnames, and millions of family names.. It's never ending shit. I don't see a future where we update such lists constantly just because there is some name missing. 

I don't think there should be _any_ clubs about names in the first place.

May family name isn't there too, but I don't care. Neither Yanev, nor Yaneff, nor Reagent.

**Comment by themichaelk** [comment]
yeah you can do what you want
