### ISSUE TITLE
Please add these common adjectives to the Adjective collection

### ISSUE THREAD

**Issue by MichaelHodosh** [Zimtente/ens-collections#487]
sated
vibrating
unzipped
investible
inscribed
delectable
reinvented
rebuilt
genderneutral
veiled
instep
nostrings
ornamental
braced
custombuilt
faceted
veiled
azorean
bullied
sweetened
pleasuring
strapping
handcuffed
certifiable
localised
inhome
formulated
shrinking
conversational
electable
tumbling
bargaining

THank you

**Comment by Zimtente** [comment]
sated - verb
vibrating - verb
unzipped - verb
investible - adj
inscribed - verb
delectable - adj
reinvented - verb
rebuilt - verb
genderneutral - adj
veiled - adj
Azorean - adj and noun
bullied - verb
sweetened - verb
pleasuring - verb
strapping - adj
handcuffed - verb
certifiable - adj
localised - verb
in-home - adj
formulated - verb
shrinking - verb
conversational - adj
electable - adj
tumbling - noun
bargaining - verb

due to https://www.merriam-webster.com/dictionary we categorized the words as listed above.

Greets Zim
