### ISSUE TITLE
Please add these nouns to the Noun Collection - thank you

### ISSUE THREAD

**Issue by MichaelHodosh** [Zimtente/ens-collections#488]
lechery
colouring
naturism
freestyles
mooring
instep
colorwheel
brainfood
strapping
tumbling
bargaining
freestyles
specialties.eth
diversions.eth
proms.eth
gokarts.eth
nannies.eth
reunions.eth
blends.eth
reformers.eth
vintners.eth
resins.eth
armaments.eth
skiboots.eth
brunettes.eth
birthsigns.eth
motorcars.eth
birthstones.eth
syrups.eth
beachvillas.eth
snowmobiles.eth
barbecues.eth
sitters.eth
fixtures.eth
jacuzzis.eth

**Comment by Zimtente** [comment]
lechery - noun
colouring - noun
naturism - noun
freestyles - pl. noun
mooring - noun
instep - noun
colorwheel -noun
brainfood - noun
strapping - noun and adj
tumbling - noun and adj
bargaining - verb
specialties - pl. noun
diversions - pl. noun
proms - pl. noun
gokarts - pl. noun
nannies - pl. noun
reunions - pl. noun
blends - pl. noun
reformers - pl. noun
vintners - pl. noun
resins - pl. noun
armaments - pl. noun
skiboots - pl. noun
brunettes - pl. noun
birth sign - pl. noun
motorcars - pl. noun
birthstones - pl. noun
syrups - pl. noun
snowmobiles - pl, noun
barbecues - pl. noun
sitters - pl. noun
fixtures - pl. noun
jacuzzis - pl. noun


have been added to listed categories above due to information on:
https://www.merriam-webster.com/dictionary

greets
