### ISSUE TITLE
Pre-Punk Issues

### ISSUE THREAD

**Issue by vpofsales** [Zimtente/ens-collections#779]
I know we got the other malformed pre-punks corrected through discord, this is my first time submitting these this way, so if you need any additional info from myself please just let me know.  

beer.com - shows null (was showing null, now not showing in profile at all. Same for the other three "." names below"
daum.net - shows null
slock.it - shows null
visa.checkout - shows null

☭☭☭☭☭☭☭ - should be palindrome
peterdeoliveirarodrigues - should be Pre-punk 10k 
chayaamylitvack - should be Pre-punk 10k
détente -Should be Pre-punk

**Comment by vpofsales** [comment]
Also would like to update prepunk #11454 vlad☺☺☺.eth 
to a similar manner of how ❤ethereum.eth is done. (tags of letters,emoji,unicode)

vlad☺☺☺.eth  
keccak256 hash: 30c873c29f379fd6cdd2fec46b821180a58aaa8e9d1d65b6353ca6166651463e
tokenid: 22065185092779534764355256869619276628393045616357253328630693687038116447806

**Comment by shukaeth** [comment]
Hi here is our feedback:

beer.com - shows null (was showing null, now not showing in profile at all. Same for the other three "." names below"
daum.net - shows null
slock.it - shows null
visa.checkout - shows null

_-> Because of the new subdomain wrapper (released by the ENS DAO) we need a workaround for these domains because they are not real subdomains. After the new release of the ENS DAO we will think about how we can support these "fake" subdomains._
___________________________________

☭☭☭☭☭☭☭ - should be palindrome

_-> Unfortunately we dont have a category for 7 character palindromes yet._

____________________________________

peterdeoliveirarodrigues - should be Pre-punk 10k
chayaamylitvack - should be Pre-punk 10k
détente -Should be Pre-punk
 vlad☺☺☺.eth
 
 _-> have been updated right now!_
 
 
 __________________________________________
 
 All the best,

shuka.eth
